### ISSUE TITLE
Add `lambda` source recovery

### ISSUE THREAD

**Issue by gordonwatts** [iris-hep/func_adl#45]
@AndrewEckart points out that recovering the `ast` from a `lambda` function isn't that difficult:

```
import inspect
import ast
sq_ast = ast.parse(inspect.getsource(lambda x: x*x))
lda = next((node for node in ast.walk(sq_ast)
                     if isinstance(node, ast.Lambda)), None)
if lda is None:
    # complain to user
```

## Motivation

This will make the source code look a lot nicer - rather than passing strings to `Select` one can now pass actual code - and further, it will allow editors and IDE's to syntax check at authorship time rather than just at run-time.

## Todo

- [x] Test inline `lambda` function
- [x] Test a function defined at global and local scope as an argument
- [x] Test nested lambda's in both cases
- [x] Update documentation
